package com.winsonchiu.rpg.tiles;

/**
 * Created by TheKeeperOfPie on 5/25/2015.
 */
public enum TileType {

    INVALID,
    PATH_VERTICAL,
    PATH_HORIZONTAL,
    PATH_TOP_LEFT,
    PATH_BOTTOM_LEFT,
    PATH_BOTTOM_RIGHT,
    PATH_TOP_RIGHT,
    PATH_T_DOWN,
    PATH_T_RIGHT,
    PATH_T_UP,
    PATH_T_LEFT,
    PATH_FLOOR,
    ROOM_T_DOWN,
    ROOM_T_RIGHT,
    ROOM_T_UP,
    ROOM_T_LEFT,
    ROOM_TOP_LEFT,
    ROOM_BOTTOM_LEFT,
    ROOM_BOTTOM_RIGHT,
    ROOM_TOP_RIGHT,
    WALL,
    GROUND,
    CHEST_LEFT_CLOSED,
    CHEST_RIGHT_CLOSED,
    CHEST_LEFT_OPEN,
    CHEST_RIGHT_OPEN,
    ROOM_GROUND,
    ROOM_FLOOR,
    STAIRS_UP_RIGHT,
    STAIRS_UP_LEFT,
    STAIRS_DOWN_RIGHT,
    STAIRS_DOWN_LEFT,

}
